[package]
name = "jam-one"
version = "0.1.0"
authors = ["Dejaime Antônio de Oliveira Neto <contact@dejai.me>"]
edition = "2018"

[dependencies]
amethyst = "0.15.1"
rand = "0.7.3"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
vulkan = ["amethyst/vulkan"]
